
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author mo-mia
 */
public class Student_Timetable extends javax.swing.JFrame {
   Timetable objTimetable;
    /**
     * Creates new form mainTimetable
     */
    public Student_Timetable() {

        initComponents();
        spinweek.setForeground(Color.WHITE);
        spinweek.setBackground(Color.BLACK);
        
        
        lblsplash.requestFocus();
            txfStuNum.setText("218000");
            butgentable.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinweek = new javax.swing.JSpinner();
        lblsplash = new javax.swing.JLabel();
        butexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaOutput = new javax.swing.JTextArea();
        butdisptable = new javax.swing.JButton();
        butgentable = new javax.swing.JButton();
        txfStuNum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaTimetable = new javax.swing.JTextArea();
        lblwall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(920, 460));
        setMinimumSize(new java.awt.Dimension(920, 460));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(920, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(920, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spinweek.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        getContentPane().add(spinweek, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 50, -1));

        lblsplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Splash.png"))); // NOI18N
        lblsplash.setMinimumSize(new java.awt.Dimension(0, 0));
        lblsplash.setPreferredSize(new java.awt.Dimension(0, 0));
        lblsplash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblsplashFocusGained(evt);
            }
        });
        getContentPane().add(lblsplash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        butexit.setBackground(new java.awt.Color(0, 0, 0));
        butexit.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        butexit.setForeground(new java.awt.Color(255, 255, 255));
        butexit.setText("X");
        butexit.setMaximumSize(new java.awt.Dimension(40, 30));
        butexit.setMinimumSize(new java.awt.Dimension(40, 30));
        butexit.setPreferredSize(new java.awt.Dimension(40, 30));
        butexit.setRequestFocusEnabled(false);
        butexit.setSelected(true);
        butexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butexitActionPerformed(evt);
            }
        });
        getContentPane().add(butexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(164, 94));

        txaOutput.setEditable(false);
        txaOutput.setBackground(new java.awt.Color(0, 0, 0));
        txaOutput.setColumns(20);
        txaOutput.setForeground(new java.awt.Color(255, 255, 255));
        txaOutput.setRows(5);
        txaOutput.setMaximumSize(new java.awt.Dimension(164, 94));
        txaOutput.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setViewportView(txaOutput);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 408));

        butdisptable.setBackground(new java.awt.Color(0, 0, 0));
        butdisptable.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        butdisptable.setForeground(new java.awt.Color(255, 255, 255));
        butdisptable.setText("Display Timetable");
        butdisptable.setMaximumSize(new java.awt.Dimension(150, 30));
        butdisptable.setMinimumSize(new java.awt.Dimension(150, 30));
        butdisptable.setPreferredSize(new java.awt.Dimension(150, 30));
        butdisptable.setSelected(true);
        butdisptable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdisptableActionPerformed(evt);
            }
        });
        getContentPane().add(butdisptable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        butgentable.setBackground(new java.awt.Color(0, 0, 0));
        butgentable.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        butgentable.setForeground(new java.awt.Color(255, 255, 255));
        butgentable.setText("New Timetable");
        butgentable.setMaximumSize(new java.awt.Dimension(150, 30));
        butgentable.setMinimumSize(new java.awt.Dimension(150, 30));
        butgentable.setPreferredSize(new java.awt.Dimension(150, 30));
        butgentable.setSelected(true);
        butgentable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butgentableActionPerformed(evt);
            }
        });
        getContentPane().add(butgentable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 5, -1, -1));

        txfStuNum.setText("Student No.");
        txfStuNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfStuNumFocusGained(evt);
            }
        });
        getContentPane().add(txfStuNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 12, 199, -1));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane2.setName(""); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(164, 94));

        txaTimetable.setEditable(false);
        txaTimetable.setBackground(new java.awt.Color(0, 0, 0));
        txaTimetable.setColumns(20);
        txaTimetable.setForeground(new java.awt.Color(255, 255, 255));
        txaTimetable.setRows(5);
        txaTimetable.setMaximumSize(new java.awt.Dimension(164, 94));
        txaTimetable.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane2.setViewportView(txaTimetable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 40, 720, 408));

        lblwall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        getContentPane().add(lblwall, new org.netbeans.lib.awtextra.AbsoluteConstraints(-600, -130, 2100, 1210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butgentableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butgentableActionPerformed
        // TODO add your handling code here:
        String timeTable[][] = new String[5][11];
        txaOutput.setText("");
        txaTimetable.setText("");
        File file = new File("Documents/studentS1data.txt");
        String StudentNumber = null;
        String student = null;
        String string = null;
        int year = 0;
        String dis = null;
        boolean valid = false;
        try {
            FileReader filRead = new FileReader(file);
            BufferedReader bufRead = new BufferedReader(filRead);

            String s = null;

            while ((s = bufRead.readLine()) != null) {
                StudentNumber = s.substring(0, s.indexOf("#"));
                if (StudentNumber.equals(txfStuNum.getText())) {
                    student = StudentNumber;
                    string = s.substring(s.indexOf("#") + 1, s.length());
                    string = string.substring(string.indexOf("#") + 1, string.length());
                    dis = string.substring(0, string.indexOf("#"));
                    string = string.substring(string.indexOf("#") + 1, string.length());
                    valid = true;
                }

            }

        } catch (IOException ex) {
            System.out.println("ERROR:\t" + ex.getMessage());
        }
        String modules[] = null;
        int modulesCount = 0;
        if (valid == true) {

            modules = string.split("#");
            modulesCount = modules.length;
            txaOutput.append("Student Number: " + student + "\n");

            txaOutput.append("Discipline: " + dis + "\n");

            txaOutput.append("Modules: ");

            for (int i = 0; i < modulesCount; i++) {
                txaOutput.append(modules[i] + "\t");
            }
            String modName = null, Type = null;
            int day_of_week = 0, period = 0;

            txaOutput.append("\n");
            File f = new File("Documents/slotS1data.txt");
            String dis2[];
            txaOutput.append("\nName:\tType:\tDay:\tPeriod:\n");
            try {
                FileReader fr = new FileReader(f);
                BufferedReader buffy = new BufferedReader(fr);
                String s;
                while ((s = buffy.readLine()) != null) {
                    String mod = s.substring(0, s.indexOf("#"));
                    for (int i = 0; i < modulesCount; i++) {
                        if (mod.equals(modules[i])) {
                            String s2 = s.substring(s.indexOf("#") + 1, s.length());
                            s2 = s2.substring(s2.indexOf("#") + 1, s2.length());
                            s2 = s2.substring(s2.indexOf("#") + 1, s2.length());
                            s2 = s2.substring(s2.indexOf("#") + 1, s2.length());
                            dis2 = s2.split("#");
                            for (int j = 0; j < dis2.length; j++) {
                                if (dis.equals(dis2[j])) {
                                    modName = s.substring(0, s.indexOf("#"));
                                    s2 = s.substring(s.indexOf("#") + 1, s.length());
                                    Type = s2.substring(0, s2.indexOf("#"));
                                    s2 = s2.substring(s2.indexOf("#") + 1, s2.length());
                                    day_of_week = Integer.parseInt(s2.substring(0, s2.indexOf("#")));
                                    s2 = s2.substring(s2.indexOf("#") + 1, s2.length());
                                    period = Integer.parseInt(s2.substring(0, s2.indexOf("#")));
                                    txaOutput.append(modName + "\t" + Type + "\t" + day_of_week + "\t" + period + "\n");
                                    for (int x = 0; x < 5; x++) {
                                        if (day_of_week == (x + 1)) {
                                            for (int y = 0; y < 11; y++) {
                                                if (period == (y + 1)) {
                                                    timeTable[x][y] = modName + "(" + Type + ")";
                                                }
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }
                }

            } catch (IOException ex) {
                System.out.println("ERROR:\t" + ex.getMessage());
            }

            //--------------------------------------------------------------------------------------------
            geneticAlgorithm GA = new geneticAlgorithm(timeTable, 1);
             objTimetable = GA.getFittedTable();

            timeTable = objTimetable.getBestTable();
            
            objTimetable.PrintToFile(student, timeTable);
            
            
            
            
            
            
            
            
            

            //----------------------------------------------------------------------------------------------------
            txaTimetable.setText("Day:\t" + "Monday\t" + "Tuesday\t" + "Wednesday\t" + "Thursday\t" + "Friday\n\n");

            for (int i = 0; i < 11; i++) {
                txaTimetable.append("Period " + (i + 1) + ":\t");
                for (int j = 0; j < 5; j++) {
                    if (timeTable[j][i] == null) {
                        txaTimetable.append("\t");
                    } else {
                        txaTimetable.append(timeTable[j][i] + "\t");
                    }

                }
                txaTimetable.append("\n");

            }

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Entry...", "ERROR", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_butgentableActionPerformed

    private void butexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_butexitActionPerformed

    private void txfStuNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfStuNumFocusGained
        // TODO add your handling code here:
        if (txfStuNum.getText().contains("Student")) {
            txfStuNum.setText("");
        }
    }//GEN-LAST:event_txfStuNumFocusGained

    private void butdisptableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdisptableActionPerformed
        // TODO add your handling code here:
String out=objTimetable.ReadFromFile("EL", txfStuNum.getText());
       txaTimetable.setText(out);
             
    

    }//GEN-LAST:event_butdisptableActionPerformed

    private void lblsplashFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblsplashFocusGained
        // TODO add your handling code here:
/*        try {
            TimeUnit.SECONDS.sleep(3);

        } catch (InterruptedException ex) {
            System.out.println("ERROR:\t" + ex.getMessage());
        }
        lblsplash.setVisible(false);*/
    }//GEN-LAST:event_lblsplashFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butdisptable;
    private javax.swing.JButton butexit;
    private javax.swing.JButton butgentable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblsplash;
    private javax.swing.JLabel lblwall;
    private javax.swing.JSpinner spinweek;
    private javax.swing.JTextArea txaOutput;
    private javax.swing.JTextArea txaTimetable;
    private javax.swing.JTextField txfStuNum;
    // End of variables declaration//GEN-END:variables
}
